# Generated by Django 4.0.5 on 2022-06-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='created_at',
        ),
    ]
