# Generated by Django 4.0.5 on 2022-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_remove_profile_created_at_remove_project_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_rating',
        ),
        migrations.AddField(
            model_name='reviews',
            name='content_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='design_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='usability_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
