# Generated by Django 4.0.5 on 2022-06-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_reviews_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
