# Generated by Django 4.0.5 on 2022-06-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_remove_reviews_review_rating_reviews_content_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='ratings',
            name='content_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='design_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='usability_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2),
        ),
    ]
