# Generated by Django 4.0.5 on 2022-06-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_reviews_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='created_at',
        ),
    ]
