# Generated by Django 4.0.5 on 2022-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_remove_ratings_created_at_remove_reviews_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
