# Generated by Django 4.0.5 on 2022-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0011_remove_project_uploaded_at_remove_reviews_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=150),
        ),
    ]
